##### UnaRL-DRL Config #####
---
##### DRL #####
IMPORTANTSAMPLING : False
ENTROPY : True
THRESHOLD : 10
TARGET_UPDATE : 1
BATCH_SIZE : 32
GAMMA : 0.99
MEMORY_CAPACITY : 20000
PREFERENCE_FREQ : 1
Q_FREQ : 1
EPS_START : 1.0
EPS_END : 0.0
EPS_DECAY : 100
MAX_NUM_EPOC : 300
MAX_NUM_STEPS : 200
PLOT_INTERVAL : 10
SAVE_INTERVAL : 20
DECISION_VARIABLE : 4
EVALUATION_EPOC : 104

##### Environment ######
AGENT_ID : 'Pianist'
env_name : 'LeftTurnCopy' #'merge'
screen_size : 120
view : 50

##### Algo ######
DQN:
    name : 'dqn'

SAC:
    name: "sac"